# Generated by Django 3.1.5 on 2021-03-24 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='email',
        ),
    ]
