# Generated by Django 3.1.5 on 2021-03-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_remove_investor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='zip_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
